### ISSUE TITLE
Snelheid vuur

### ISSUE THREAD

**Issue by swennijboer** [swennijboer/IntroProject#40]
De snelheid van het vuur wordt nog niet aangepast door de animatie snelheid
Ook moet het vuur op "pauze" gaan als de mensen op pauze gaan

**Comment by Riscky** [comment]
Voor het oplossen van deze bug zul je er baat bij hebben dat Vuur nu een eigen AI (AIVuur heeft).
Zie mijn commit voor meer uitleg
