### ISSUE TITLE
SwenForm verwijderen

### ISSUE THREAD

**Issue by Riscky** [swennijboer/IntroProject#48]

**Comment by swennijboer** [comment]
Waarom? Tis soms handig om te testen en het loopt volledig naast het programma, of geeft hij nu errors?

**Comment by Riscky** [comment]
is cleaner, en we hebben het niet meer nodig
Ik heb m ook als enhancement gelabeld

**Comment by swennijboer** [comment]
Ah oke, ik zal het thuis weghalen.
Ik maak dan wel een backup van het bestand, just in case.
Maar ik zal hem uit de git repo halen
