### ISSUE TITLE
Kruisje bij mensen als ze dood zijn

### ISSUE THREAD

**Issue by swennijboer** [swennijboer/IntroProject#50]
Laat een kruisje op de plaats verschijnen van een dood mens

**Comment by Riscky** [comment]
Hoe kom ik te weten hoe een mens dood is? is daar een propertie voor in AIMens?

**Comment by swennijboer** [comment]
Kan nog niet, een mens kan nog niet dood gaan. Ik geef wel een seintje zodra dit werkt
